### ISSUE TITLE
Not actually an issue, but i'm inrested to know how apps can gather list of installed apps on the phone

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [databurn-in/PrivacyBreacher#4]
as title says, i want to know how it works especially after FB did it

**Comment by NandanDesai** [comment]
Check out the point 6 in this article: https://github.com/databurn-in/Android-Privacy-Issues

You'll get the details there.

**Comment by EsmailELBoBDev2** [comment]
Thank you!
